SELECT CONCAT(TABLE_NAME,'.', COLUMN_NAME) as Import_text, TABLE_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Tmp_Type_Seq_Table' AND COLUMN_NAME<>'id_A'

UNION

SELECT CONCAT(TABLE_NAME,'.', COLUMN_NAME) as Import_text, TABLE_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Tmp_UF_Dim_Table' AND COLUMN_NAME<>'id_A'

UNION   

SELECT CONCAT(TABLE_NAME,'.', COLUMN_NAME) as Import_text, TABLE_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Tmp_UF_Table' AND COLUMN_NAME<>'id_A'

UNION

SELECT CONCAT(TABLE_NAME,'.', COLUMN_NAME) as Import_text, TABLE_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Tmp_NGAP_Table' AND COLUMN_NAME<>'id_A'

UNION

SELECT CONCAT(TABLE_NAME,'.', COLUMN_NAME) as Import_text, TABLE_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Tmp_CCAM_Table' AND COLUMN_NAME<>'id_A'

UNION

SELECT CONCAT(TABLE_NAME,'.', COLUMN_NAME) as Import_text, TABLE_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Tmp_INX_Table' AND COLUMN_NAME<>'id_A'

UNION

SELECT CONCAT(TABLE_NAME,'.', COLUMN_NAME) as Import_text, TABLE_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Tmp_UFH_Table' AND COLUMN_NAME<>'id_A'

UNION

SELECT CONCAT(TABLE_NAME,'.', COLUMN_NAME) as Import_text, TABLE_NAME, ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'Tmp_Code_Equip_Table' AND COLUMN_NAME<>'id_A'

ORDER BY TABLE_NAME, ORDINAL_POSITION